INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Baker', 30134);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Banquet manager', 20495);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Bartender', 38651);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Beverage manager', 31989);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Broiler cook', 39565);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Bus person', 71314);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Catering manager', 94993);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Counter server', 15246);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Dining room manager', 12493);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Executive chef', 31723);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Expediter', 54650);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Food and  beverage director', 44751);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Foodservice directory (health care)', 11250);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'General manager (fullservice)', 95538);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'General manager (quick service)', 93879);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Human resources manager', 56127);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Kitchen manager', 55034);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Pantry cook', 85519);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Pastry chef', 82986);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'President/CEO', 199262);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Public relations manager', 75242);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Server', 32232);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Soup and sauce cook', 76741);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Sous chef', 81502);
INSERT INTO POSITION(PositionID, Title, Salary) VALUES(pos_id_seq.nextval, 'Wine steward', 57270);