ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';

INSERT INTO POSITION (PositionID, Title, Salary) VALUES (1, 'Banquetmanager', 2049);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (2, 'Bartender', 3865);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (3, 'Beveragemanager', 3198);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (4, 'Broilercook', 3956);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (5, 'Busperson', 7131);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (6, 'Cateringmanager', 9499);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (7, 'Counterserver', 1524);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (8, 'Diningroommanager', 1249);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (9, 'Executivechef', 3172);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (10, 'Expediter', 5465);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (11, 'Foodandbeveragedirector', 4475);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (12, 'Foodservicedirectory(healthcare)', 1125);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (13, 'Generalmanager(fullservice)', 9553);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (14, 'Generalmanager(quickservice)', 9387);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (15, 'Humanresourcesmanager', 5612);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (16, 'Kitchenmanager', 5503);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (17, 'Pantrycook', 8551);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (18, 'Pastrychef', 8298);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (19, 'President/CEO', 19926);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (20, 'Publicrelationsmanager', 7524);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (21, 'Server', 3223);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (22, 'Soupandsaucecook', 7674);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (23, 'Souschef', 8150);
INSERT INTO POSITION (PositionID, Title, Salary) VALUES (24, 'Winesteward', 5727);