CREATE SEQUENCE pos_id_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
/ 
 CREATE SEQUENCE emp_id_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 /
 CREATE SEQUENCE sched_id_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 /
 CREATE SEQUENCE recp_id_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 /
 CREATE SEQUENCE cl_id_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 /
 CREATE SEQUENCE ingr_id_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 /
 CREATE SEQUENCE recp_dt_id_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 /
 CREATE SEQUENCE ingr_st_id_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 /
 CREATE SEQUENCE supl_req_id_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 /
 CREATE SEQUENCE supl_st_id_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 /
 CREATE SEQUENCE supl_id_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 /
 CREATE SEQUENCE resrs_id_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 /