insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (912, 392, 'morbi vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (730, 668, 'sem duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (857, 1514, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (433, 387, 'duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (349, 1132, 'sem praesent');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (352, 1859, 'sagittis sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (272, 1717, 'diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (479, 87, 'fringilla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (630, 462, 'eu felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (502, 333, 'auctor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (916, 1566, 'eleifend pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (645, 1400, 'convallis duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (982, 912, 'orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (177, 1487, 'commodo vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (227, 273, 'aliquam sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (611, 1676, 'hac habitasse');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (302, 815, 'semper sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (556, 1655, 'turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (442, 1421, 'proin leo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (338, 498, 'justo sollicitudin');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (4, 1115, 'consequat varius');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (635, 1798, 'dolor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (705, 598, 'cubilia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (721, 363, 'sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (958, 599, 'duis aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (704, 903, 'erat curabitur');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (155, 1180, 'adipiscing');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (786, 1252, 'nisi nam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (885, 1406, 'montes nascetur');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (920, 1376, 'mattis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (735, 1272, 'diam erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (806, 1919, 'aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (623, 65, 'augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (37, 935, 'libero');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (888, 1630, 'sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (981, 640, 'tempus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (196, 1515, 'non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (763, 548, 'nulla nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (864, 1632, 'risus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (207, 641, 'sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (892, 511, 'nonummy integer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (664, 757, 'vitae ipsum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (101, 563, 'metus sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (771, 1275, 'elementum ligula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (934, 522, 'faucibus orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (146, 712, 'sapien a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (341, 229, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (98, 1678, 'dictumst morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (496, 422, 'quisque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (497, 575, 'viverra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (6, 1919, 'consequat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (95, 950, 'duis bibendum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (95, 1782, 'quis turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (239, 1111, 'cursus id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (298, 1192, 'erat id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (397, 801, 'potenti');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (154, 929, 'ac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (880, 326, 'accumsan');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (479, 448, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (119, 901, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (827, 702, 'in faucibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (604, 659, 'tortor id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (458, 1313, 'euismod');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (623, 1065, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (75, 515, 'nunc nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (359, 1582, 'ipsum primis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (361, 383, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (199, 1647, 'odio');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (695, 615, 'ultrices aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (887, 1311, 'augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (717, 618, 'amet nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (774, 1469, 'quis tortor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (202, 323, 'nec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (798, 95, 'ipsum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (448, 128, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (655, 1321, 'parturient montes');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (956, 2000, 'purus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (266, 1972, 'non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (881, 1914, 'magna at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (973, 1192, 'aenean sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (527, 636, 'nam ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (939, 856, 'consectetuer eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (180, 1955, 'iaculis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (741, 1842, 'vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (14, 1311, 'dapibus duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (794, 1032, 'faucibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (893, 1963, 'platea');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (169, 1486, 'pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (733, 55, 'quis augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (406, 1296, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (914, 214, 'amet turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (636, 498, 'ornare');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (987, 1568, 'sed lacus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (354, 870, 'maecenas leo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (576, 1645, 'quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (206, 280, 'viverra eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (795, 756, 'neque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (461, 718, 'lacus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (818, 1881, 'ac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (531, 1440, 'montes');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (381, 1182, 'varius');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (757, 676, 'etiam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (998, 1959, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (176, 779, 'in felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (929, 1754, 'in consequat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (988, 960, 'ut dolor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (756, 542, 'suspendisse');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (162, 1902, 'dolor sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (629, 261, 'tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (144, 1351, 'rutrum nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (275, 1849, 'turpis sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (842, 1505, 'tellus in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (630, 1882, 'lorem id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (717, 1321, 'sed nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (503, 1629, 'sollicitudin');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (7, 1784, 'lectus aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (162, 786, 'luctus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (625, 883, 'nulla facilisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (71, 830, 'curabitur at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (826, 1613, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (216, 1501, 'bibendum imperdiet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (270, 401, 'sapien in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (981, 785, 'nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (863, 1983, 'nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (373, 1649, 'consequat in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (91, 721, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (973, 1471, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (401, 1878, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (434, 1833, 'posuere cubilia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (457, 714, 'elit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (132, 1565, 'vel pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (866, 1723, 'magna');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (449, 197, 'dui vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (733, 679, 'velit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (578, 1601, 'nisi eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (868, 528, 'potenti nullam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (70, 1059, 'quisque porta');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (282, 948, 'ante');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (611, 1912, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (928, 1175, 'convallis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (456, 1670, 'tempus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (454, 735, 'in congue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (107, 1038, 'suscipit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (874, 689, 'tempus vivamus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (438, 424, 'sollicitudin');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (299, 1378, 'venenatis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (403, 247, 'dictumst aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (406, 336, 'porttitor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (311, 1121, 'fermentum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (234, 121, 'non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (792, 1918, 'eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (395, 1140, 'sem duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (483, 663, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (346, 125, 'erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (508, 969, 'eleifend');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (253, 384, 'enim');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (666, 618, 'ligula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (87, 1087, 'massa quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (914, 1573, 'enim lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (504, 454, 'cras');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (297, 1377, 'vivamus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (154, 1049, 'sem praesent');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (522, 1558, 'ipsum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (695, 1792, 'erat quisque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (959, 1530, 'a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (794, 1876, 'mauris vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (85, 328, 'viverra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (933, 1017, 'velit vivamus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (208, 1891, 'semper interdum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (203, 1691, 'diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (166, 1697, 'risus auctor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (541, 529, 'vulputate vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (139, 1074, 'semper interdum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (659, 175, 'habitasse');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (397, 953, 'pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (795, 1791, 'sapien in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (543, 1928, 'nec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (955, 522, 'convallis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (487, 528, 'odio justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (382, 1922, 'sem mauris');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (155, 796, 'semper');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (594, 656, 'ut blandit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (227, 97, 'dictumst');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (491, 1039, 'fusce congue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (559, 51, 'aliquet pulvinar');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (889, 1504, 'ut dolor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (334, 261, 'quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (217, 1862, 'vitae nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (681, 474, 'risus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (264, 1133, 'montes nascetur');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (302, 1125, 'ac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (663, 54, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (750, 1007, 'penatibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (58, 461, 'pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (354, 720, 'parturient montes');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (669, 1405, 'morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (925, 1536, 'neque sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (821, 1362, 'volutpat sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (121, 1998, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (929, 840, 'sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (528, 1503, 'duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (248, 1956, 'nisl nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (172, 1297, 'suscipit a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (143, 945, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (556, 2, 'nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (744, 982, 'nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (601, 641, 'ornare');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (590, 1960, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (997, 853, 'dapibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (740, 558, 'massa id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (846, 1477, 'integer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (19, 67, 'augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (571, 314, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (539, 13, 'massa');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (379, 1466, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (795, 684, 'venenatis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (775, 1836, 'pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (872, 1248, 'non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (950, 1663, 'quam pharetra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (652, 1852, 'convallis morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (126, 37, 'at velit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (962, 466, 'magnis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (177, 133, 'curae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (529, 333, 'a odio');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (87, 1263, 'congue diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (589, 1411, 'vitae quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (332, 1068, 'risus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (267, 700, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (988, 1959, 'sagittis sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (105, 335, 'consectetuer adipiscing');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (455, 547, 'ac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (511, 993, 'lacus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (672, 919, 'elementum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (308, 1025, 'parturient montes');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (187, 481, 'eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (488, 279, 'nulla neque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (210, 702, 'adipiscing');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (152, 60, 'et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (970, 193, 'luctus et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (268, 1253, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (467, 611, 'vestibulum sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (460, 636, 'sed tristique');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (39, 1650, 'sollicitudin vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (858, 113, 'eu massa');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (602, 1222, 'duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (425, 188, 'viverra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (315, 1368, 'donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (833, 16, 'libero');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (451, 715, 'eu interdum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (868, 160, 'sed augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (534, 1610, 'quisque ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (271, 132, 'a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (8, 1111, 'dictumst etiam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (878, 1881, 'sollicitudin ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (231, 1820, 'potenti in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (949, 1597, 'pretium');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (480, 367, 'metus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (90, 928, 'sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (417, 848, 'vestibulum eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (351, 1892, 'luctus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (416, 1903, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (661, 1268, 'est');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (673, 1462, 'eros suspendisse');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (357, 1430, 'viverra pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (801, 1637, 'vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (668, 1913, 'posuere');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (228, 1639, 'lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (817, 36, 'cursus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (591, 168, 'et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (21, 1803, 'egestas metus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (16, 78, 'feugiat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (930, 785, 'tellus nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (278, 1257, 'velit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (238, 1145, 'fusce');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (91, 1463, 'pretium');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (697, 376, 'eget tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (672, 1155, 'dui');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (43, 1102, 'et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (397, 1107, 'ut erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (328, 1359, 'eleifend');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (647, 1987, 'condimentum curabitur');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (116, 1148, 'libero');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (546, 1600, 'pharetra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (812, 1034, 'rhoncus aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (499, 1933, 'sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (461, 1285, 'lobortis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (118, 1195, 'neque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (479, 656, 'sed tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (780, 708, 'aenean fermentum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (507, 1593, 'eu felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (845, 1326, 'et ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (969, 860, 'quisque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (781, 491, 'sodales');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (422, 1267, 'quis odio');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (255, 318, 'dolor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (629, 1325, 'eleifend');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (219, 1432, 'amet consectetuer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (666, 461, 'ipsum dolor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (482, 851, 'diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (993, 355, 'venenatis tristique');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (591, 1765, 'mauris');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (247, 98, 'dui');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (306, 1059, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (946, 857, 'a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (912, 714, 'aenean');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (144, 1897, 'semper rutrum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (215, 1514, 'imperdiet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (31, 1009, 'ultricies eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (39, 914, 'turpis sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (888, 972, 'aliquet pulvinar');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (385, 1274, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (274, 1252, 'justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (504, 75, 'habitasse platea');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (545, 1585, 'magna');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (276, 15, 'eget massa');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (960, 1472, 'et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (165, 1261, 'vulputate nonummy');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (606, 912, 'faucibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (398, 127, 'quis turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (308, 1697, 'lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (996, 59, 'iaculis diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (240, 1150, 'volutpat sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (469, 1757, 'nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (109, 1987, 'nullam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (521, 1342, 'facilisi cras');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (574, 817, 'quam suspendisse');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (627, 1921, 'gravida');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (961, 546, 'sagittis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (977, 1756, 'potenti');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (742, 490, 'fusce lacus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (80, 559, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (96, 1621, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (691, 1264, 'porttitor lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (817, 47, 'odio condimentum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (145, 368, 'nam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (579, 1387, 'magna');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (113, 1017, 'nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (703, 92, 'curabitur at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (451, 350, 'enim');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (798, 841, 'eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (119, 1309, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (361, 1422, 'mauris ullamcorper');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (843, 956, 'odio curabitur');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (615, 191, 'quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (783, 1548, 'justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (465, 972, 'sem sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (939, 1658, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (648, 1342, 'augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (442, 1208, 'mus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (711, 365, 'magnis dis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (513, 40, 'ante vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (963, 1380, 'et eros');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (915, 449, 'justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (589, 1418, 'ipsum aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (574, 174, 'accumsan');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (671, 1759, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (694, 922, 'nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (776, 316, 'urna ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (281, 267, 'tincidunt in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (698, 157, 'viverra eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (349, 1167, 'purus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (167, 1462, 'pellentesque viverra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (873, 95, 'donec posuere');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (521, 544, 'nulla sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (512, 12, 'dolor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (734, 1085, 'purus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (917, 1450, 'augue a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (129, 630, 'neque sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (440, 59, 'sapien dignissim');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (18, 931, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (556, 95, 'interdum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (663, 1315, 'eu felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (160, 698, 'ipsum aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (812, 827, 'dui nec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (387, 1124, 'nec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (835, 1382, 'justo morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (868, 1321, 'et ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (85, 579, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (100, 144, 'velit nec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (554, 719, 'donec vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (74, 1115, 'cubilia curae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (719, 1395, 'congue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (927, 1666, 'vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (597, 576, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (956, 611, 'blandit non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (660, 380, 'et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (517, 1689, 'integer a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (252, 1028, 'blandit nam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (782, 411, 'volutpat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (197, 1792, 'maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (790, 1073, 'iaculis congue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (815, 287, 'suspendisse potenti');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (193, 964, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (176, 111, 'consequat lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (722, 72, 'pulvinar');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (234, 495, 'odio consequat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (254, 1023, 'pulvinar');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (283, 1299, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (368, 573, 'enim in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (101, 1906, 'ac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (146, 851, 'ut erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (769, 721, 'convallis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (796, 217, 'lobortis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (176, 945, 'rutrum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (993, 167, 'sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (608, 1727, 'accumsan');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (757, 1314, 'aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (596, 1340, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (998, 279, 'risus semper');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (373, 111, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (490, 1230, 'donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (602, 1257, 'fusce');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (708, 704, 'pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (706, 596, 'mauris vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (73, 1884, 'integer pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (704, 241, 'ipsum aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (65, 1101, 'morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (105, 433, 'sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (275, 1853, 'donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (410, 1596, 'eros viverra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (662, 1027, 'ultrices aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (928, 846, 'condimentum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (474, 71, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (49, 1044, 'molestie');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (198, 862, 'eget semper');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (981, 661, 'vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (81, 1477, 'posuere');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (99, 1132, 'dapibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (566, 395, 'quisque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (556, 1441, 'purus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (296, 574, 'nunc proin');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (703, 967, 'sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (158, 1139, 'at turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (384, 238, 'sem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (495, 1935, 'suspendisse accumsan');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (737, 1111, 'cubilia curae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (5, 1662, 'quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (65, 1958, 'at nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (921, 1404, 'sed augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (371, 112, 'gravida');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (87, 1406, 'tellus in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (97, 1030, 'sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (283, 1497, 'proin interdum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (46, 1864, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (409, 1662, 'fermentum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (582, 887, 'nulla dapibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (422, 1707, 'sapien non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (801, 1301, 'suspendisse accumsan');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (382, 1192, 'massa tempor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (711, 1706, 'libero');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (93, 867, 'duis aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (563, 1469, 'neque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (937, 861, 'pede ullamcorper');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (822, 767, 'diam cras');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (468, 1584, 'nullam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (592, 555, 'sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (375, 900, 'non interdum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (39, 1808, 'justo aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (593, 661, 'vitae ipsum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (814, 1865, 'iaculis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (924, 132, 'condimentum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (656, 806, 'turpis eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (445, 1328, 'tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (977, 1937, 'viverra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (492, 1276, 'lorem integer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (671, 1444, 'vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (263, 1394, 'elementum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (940, 772, 'platea');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (594, 1884, 'a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (99, 1043, 'elementum nullam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (884, 1393, 'blandit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (39, 1528, 'sem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (836, 1701, 'proin eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (810, 699, 'in hac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (224, 1662, 'quam fringilla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (938, 1062, 'phasellus sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (105, 786, 'lobortis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (71, 1431, 'enim');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (870, 1961, 'malesuada');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (127, 1879, 'pede justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (637, 925, 'risus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (329, 1595, 'morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (80, 643, 'aenean auctor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (306, 1953, 'amet sem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (483, 1130, 'felis sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (243, 82, 'lectus aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (71, 1838, 'dolor vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (25, 391, 'lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (283, 1876, 'morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (185, 1552, 'dui');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (415, 530, 'nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (415, 1531, 'justo morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (418, 1810, 'morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (367, 1356, 'vivamus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (277, 478, 'fusce congue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (733, 1616, 'et tempus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (466, 742, 'ut dolor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (303, 93, 'posuere felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (353, 1828, 'augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (430, 230, 'pellentesque ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (360, 1633, 'eget semper');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (136, 647, 'ut nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (800, 974, 'duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (305, 546, 'elementum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (384, 845, 'erat quisque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (815, 577, 'porttitor id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (260, 1283, 'felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (315, 1804, 'consectetuer eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (69, 602, 'laoreet ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (778, 1254, 'quam sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (795, 1558, 'sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (660, 830, 'rutrum nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (795, 795, 'placerat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (788, 219, 'volutpat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (381, 1333, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (725, 562, 'ultrices posuere');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (807, 170, 'parturient montes');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (978, 1655, 'ultrices vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (939, 1473, 'quisque ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (593, 642, 'eros');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (582, 1044, 'nisl duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (23, 275, 'vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (62, 1332, 'porttitor pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (159, 710, 'dolor morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (962, 414, 'quisque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (502, 721, 'quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (887, 1633, 'tempus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (718, 891, 'nibh');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (669, 471, 'quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (210, 1421, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (111, 701, 'molestie');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (631, 914, 'turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (303, 1350, 'nec molestie');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (851, 18, 'vulputate vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (926, 1647, 'dolor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (511, 1407, 'amet consectetuer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (813, 1667, 'odio');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (573, 1007, 'morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (707, 820, 'ullamcorper');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (400, 1572, 'ac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (544, 546, 'odio elementum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (622, 1195, 'dui');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (777, 484, 'rutrum at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (352, 280, 'amet eros');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (548, 1248, 'sem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (951, 1367, 'pretium nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (977, 281, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (963, 1115, 'volutpat erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (446, 1424, 'habitasse');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (344, 817, 'sollicitudin mi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (302, 160, 'vel est');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (831, 11, 'nec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (279, 888, 'auctor sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (882, 448, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (754, 1480, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (699, 1897, 'integer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (317, 1753, 'sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (794, 1774, 'magna vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (952, 1528, 'purus phasellus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (523, 1973, 'eleifend luctus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (827, 379, 'convallis duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (408, 260, 'odio justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (261, 125, 'mollis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (848, 383, 'ullamcorper purus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (346, 306, 'neque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (931, 1696, 'eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (428, 58, 'duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (754, 1704, 'lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (563, 1490, 'pellentesque eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (728, 1191, 'curabitur convallis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (294, 1929, 'quam a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (606, 1814, 'dictumst morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (554, 147, 'nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (265, 1608, 'aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (427, 52, 'eget tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (197, 1317, 'imperdiet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (481, 319, 'metus vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (312, 29, 'ullamcorper');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (808, 603, 'purus sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (578, 692, 'et magnis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (824, 1811, 'lacinia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (223, 898, 'nulla sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (150, 271, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (980, 220, 'neque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (527, 670, 'volutpat in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (384, 1470, 'felis sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (654, 216, 'lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (709, 1830, 'ornare');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (382, 348, 'tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (156, 1150, 'mattis nibh');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (675, 46, 'nulla neque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (573, 1263, 'enim');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (515, 1338, 'sem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (318, 1711, 'nisl nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (58, 721, 'porttitor id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (774, 1974, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (156, 992, 'phasellus in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (830, 1226, 'ipsum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (503, 1849, 'commodo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (525, 443, 'fusce');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (122, 968, 'quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (305, 1613, 'vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (951, 585, 'purus sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (597, 961, 'morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (825, 1826, 'nullam molestie');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (352, 552, 'nibh');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (709, 1813, 'lorem vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (439, 862, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (279, 912, 'sagittis nam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (531, 1390, 'luctus ultricies');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (73, 660, 'hac habitasse');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (660, 1989, 'augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (465, 185, 'pulvinar');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (475, 1444, 'ut massa');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (812, 1681, 'congue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (516, 29, 'nec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (997, 1617, 'venenatis turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (886, 1248, 'nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (492, 1051, 'fringilla rhoncus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (221, 1908, 'lorem vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (620, 407, 'enim');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (194, 1985, 'nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (333, 1848, 'sed justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (853, 1529, 'ridiculus mus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (703, 358, 'metus vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (164, 1678, 'neque vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (548, 425, 'vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (852, 1663, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (688, 644, 'quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (319, 175, 'in blandit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (207, 1809, 'potenti');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (791, 490, 'primis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (648, 38, 'mi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (182, 1281, 'pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (993, 1126, 'ligula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (229, 1638, 'vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (435, 240, 'phasellus sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (255, 518, 'nec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (871, 1444, 'pede malesuada');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (109, 411, 'et ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (427, 1344, 'sapien ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (336, 859, 'leo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (648, 1207, 'sed interdum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (59, 607, 'dictumst maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (931, 959, 'eros elementum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (833, 568, 'et ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (243, 1830, 'donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (927, 542, 'accumsan tellus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (316, 238, 'enim sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (713, 356, 'ridiculus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (903, 862, 'nibh');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (667, 1368, 'aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (914, 1299, 'ac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (823, 1178, 'quam turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (169, 70, 'ipsum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (151, 1349, 'augue aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (992, 21, 'orci luctus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (861, 480, 'at feugiat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (329, 60, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (321, 264, 'pede lobortis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (229, 1431, 'posuere felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (55, 1875, 'pede posuere');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (641, 677, 'dignissim vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (602, 1724, 'blandit ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (671, 642, 'volutpat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (843, 301, 'in tempus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (510, 833, 'vestibulum rutrum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (147, 1609, 'purus eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (92, 1071, 'adipiscing molestie');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (27, 1941, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (174, 1726, 'cubilia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (195, 1333, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (21, 1529, 'suspendisse potenti');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (360, 1397, 'integer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (79, 226, 'consequat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (218, 1377, 'bibendum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (167, 1694, 'in quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (498, 850, 'ligula nec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (401, 869, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (994, 1894, 'justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (376, 1246, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (705, 75, 'sapien cum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (565, 1223, 'non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (189, 171, 'lacus curabitur');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (698, 1087, 'dui vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (223, 825, 'lobortis ligula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (241, 745, 'luctus et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (313, 735, 'interdum mauris');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (289, 79, 'primis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (904, 1216, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (155, 103, 'pulvinar');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (451, 1208, 'varius integer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (136, 18, 'eu magna');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (157, 1118, 'vestibulum sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (730, 1743, 'posuere');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (605, 1747, 'nascetur');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (770, 888, 'mus etiam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (124, 34, 'erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (993, 671, 'penatibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (659, 1452, 'turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (944, 780, 'mauris laoreet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (758, 193, 'vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (676, 190, 'morbi odio');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (390, 866, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (677, 1184, 'phasellus in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (929, 1770, 'et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (862, 61, 'eu tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (493, 1512, 'odio');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (641, 287, 'leo maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (895, 1626, 'consequat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (996, 1614, 'mi in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (280, 1718, 'natoque penatibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (656, 127, 'pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (975, 1174, 'tincidunt ante');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (120, 617, 'mi sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (38, 497, 'donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (621, 894, 'nulla tellus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (49, 469, 'ante');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (927, 1053, 'semper');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (42, 1108, 'hac habitasse');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (102, 1081, 'odio');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (329, 835, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (454, 1019, 'augue vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (677, 1421, 'dapibus duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (595, 1656, 'magna');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (549, 1057, 'tincidunt lacus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (953, 524, 'luctus et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (349, 1315, 'laoreet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (946, 173, 'proin at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (101, 1865, 'nec nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (421, 604, 'interdum mauris');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (99, 1823, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (877, 1234, 'quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (60, 1032, 'rutrum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (759, 264, 'dapibus augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (268, 1112, 'sapien a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (822, 633, 'non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (327, 1700, 'arcu sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (549, 1588, 'erat vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (513, 839, 'vel accumsan');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (115, 1011, 'aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (314, 668, 'nonummy');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (736, 1891, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (587, 1882, 'et magnis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (274, 1817, 'maecenas leo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (576, 403, 'ligula pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (624, 1667, 'fermentum donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (428, 1947, 'sed vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (342, 684, 'ultrices posuere');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (591, 1405, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (954, 934, 'libero non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (803, 1794, 'aliquam convallis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (524, 1357, 'ac neque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (527, 591, 'arcu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (881, 108, 'quam a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (251, 1043, 'cubilia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (178, 1869, 'nunc donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (581, 219, 'odio consequat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (188, 131, 'mauris enim');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (995, 1674, 'maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (952, 193, 'tristique');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (278, 55, 'adipiscing');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (187, 816, 'libero');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (20, 1659, 'donec odio');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (821, 862, 'primis in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (201, 893, 'dapibus nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (762, 1242, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (705, 241, 'nisl venenatis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (998, 1147, 'curabitur in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (655, 1216, 'arcu adipiscing');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (5, 1490, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (372, 57, 'in sagittis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (907, 728, 'faucibus accumsan');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (759, 1611, 'dolor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (123, 415, 'integer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (382, 373, 'sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (216, 1709, 'donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (462, 1580, 'vestibulum velit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (642, 827, 'libero');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (423, 1779, 'sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (809, 575, 'viverra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (100, 165, 'justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (271, 167, 'pharetra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (220, 1928, 'massa donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (554, 970, 'massa volutpat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (907, 1616, 'quis lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (918, 70, 'quam fringilla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (705, 348, 'ut massa');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (408, 1423, 'eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (892, 1213, 'integer non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (38, 1792, 'pellentesque quisque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (863, 1459, 'vestibulum rutrum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (364, 191, 'cubilia curae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (754, 664, 'sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (498, 692, 'integer non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (496, 1815, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (613, 832, 'cum sociis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (376, 1794, 'sodales');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (150, 1848, 'accumsan');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (29, 1209, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (738, 397, 'ante nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (934, 985, 'justo pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (837, 1788, 'ligula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (483, 308, 'porttitor pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (359, 280, 'id lobortis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (279, 686, 'vel pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (698, 1383, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (503, 848, 'cras');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (863, 638, 'faucibus orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (112, 1364, 'cubilia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (241, 407, 'eleifend quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (699, 745, 'posuere nonummy');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (763, 58, 'odio');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (785, 264, 'arcu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (460, 429, 'pharetra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (895, 1784, 'tortor quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (215, 1440, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (278, 1685, 'ut mauris');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (210, 1147, 'semper');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (572, 598, 'aenean');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (337, 757, 'duis aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (939, 919, 'nam ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (356, 1276, 'et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (170, 657, 'non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (71, 1199, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (239, 592, 'ut ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (779, 879, 'pede venenatis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (745, 260, 'orci luctus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (901, 100, 'nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (109, 305, 'auctor gravida');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (836, 1488, 'felis sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (645, 792, 'mi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (513, 1159, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (205, 1058, 'aenean auctor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (313, 928, 'enim');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (548, 247, 'aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (849, 1544, 'mi nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (239, 538, 'integer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (180, 1865, 'integer a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (951, 256, 'donec posuere');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (464, 271, 'primis in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (485, 1787, 'nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (673, 1460, 'justo sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (391, 1088, 'consequat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (489, 748, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (854, 1650, 'dis parturient');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (592, 266, 'parturient montes');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (176, 369, 'ac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (430, 1072, 'aliquet maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (527, 1436, 'in hac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (959, 1926, 'eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (655, 783, 'quam fringilla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (952, 1459, 'arcu libero');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (30, 113, 'quam fringilla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (169, 1163, 'quisque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (902, 1921, 'id consequat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (760, 1673, 'mauris');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (617, 1557, 'in quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (948, 1134, 'quis turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (224, 1510, 'quisque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (622, 981, 'sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (207, 18, 'porttitor pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (752, 566, 'ultrices mattis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (812, 370, 'faucibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (408, 92, 'ac neque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (636, 1136, 'convallis morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (793, 107, 'cum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (488, 1934, 'in faucibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (399, 247, 'eget vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (881, 1598, 'nonummy maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (335, 1893, 'quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (503, 1755, 'quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (168, 1390, 'placerat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (487, 635, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (521, 101, 'commodo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (59, 1029, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (342, 90, 'nam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (133, 703, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (333, 1932, 'libero convallis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (205, 512, 'dictumst aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (495, 1809, 'ligula in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (223, 122, 'luctus ultricies');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (550, 1032, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (768, 452, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (102, 546, 'a nibh');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (451, 339, 'volutpat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (758, 17, 'primis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (479, 587, 'sapien varius');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (441, 1204, 'lobortis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (929, 343, 'vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (915, 1131, 'lobortis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (415, 1122, 'vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (123, 1501, 'lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (465, 276, 'felis ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (48, 705, 'cum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (246, 1685, 'adipiscing lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (493, 1754, 'mi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (276, 790, 'nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (178, 1658, 'nunc nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (995, 1763, 'blandit mi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (341, 1754, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (388, 388, 'pellentesque at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (439, 498, 'augue quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (105, 1313, 'pharetra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (480, 266, 'eget vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (737, 1086, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (757, 1954, 'cubilia curae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (805, 517, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (680, 504, 'erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (883, 1860, 'dolor sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (965, 541, 'interdum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (288, 658, 'semper est');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (68, 1394, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (5, 1294, 'turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (403, 349, 'parturient');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (441, 1011, 'ultrices aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (891, 1283, 'egestas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (610, 63, 'vulputate nonummy');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (196, 1115, 'tellus nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (677, 1116, 'adipiscing elit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (170, 477, 'nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (908, 1498, 'dictumst');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (559, 400, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (652, 999, 'justo maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (232, 557, 'nunc vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (641, 1225, 'felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (488, 99, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (308, 1982, 'platea');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (754, 547, 'metus aenean');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (642, 1702, 'varius ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (589, 623, 'velit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (272, 1049, 'id pretium');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (547, 1098, 'scelerisque mauris');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (15, 1823, 'vel nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (283, 1557, 'ultrices phasellus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (42, 780, 'tortor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (60, 1812, 'risus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (645, 567, 'nisi at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (287, 1593, 'a ipsum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (116, 1411, 'pretium iaculis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (311, 573, 'nulla ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (831, 20, 'pellentesque volutpat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (856, 612, 'mi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (919, 1458, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (619, 18, 'sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (333, 1849, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (475, 1914, 'dictumst etiam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (411, 128, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (798, 1279, 'dapibus at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (935, 593, 'orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (271, 772, 'morbi a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (35, 922, 'fringilla rhoncus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (581, 1938, 'sed magna');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (868, 678, 'morbi ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (224, 1274, 'ultrices erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (351, 925, 'platea');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (518, 953, 'a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (847, 997, 'libero convallis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (389, 1039, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (101, 793, 'vestibulum sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (161, 1173, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (261, 317, 'tellus semper');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (528, 1147, 'praesent');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (82, 624, 'vulputate ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (244, 1263, 'fusce congue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (361, 272, 'consectetuer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (300, 439, 'enim leo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (187, 677, 'est risus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (487, 1249, 'justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (756, 875, 'sem praesent');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (583, 962, 'aliquet massa');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (278, 1930, 'neque duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (69, 878, 'ut suscipit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (467, 455, 'praesent lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (833, 410, 'tortor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (432, 1683, 'mus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (357, 1856, 'maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (79, 1096, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (155, 1668, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (797, 418, 'felis fusce');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (772, 1132, 'elementum in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (769, 228, 'id consequat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (555, 956, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (874, 355, 'elit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (150, 1737, 'quam pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (650, 1347, 'dictumst');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (160, 968, 'ut erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (889, 118, 'lobortis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (148, 1574, 'non ligula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (887, 974, 'pulvinar');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (918, 699, 'felis fusce');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (940, 777, 'velit donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (216, 1811, 'primis in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (243, 1985, 'lacinia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (870, 487, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (207, 394, 'iaculis congue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (556, 436, 'tristique tortor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (125, 337, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (735, 1685, 'vestibulum vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (722, 1976, 'consectetuer adipiscing');
