insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (111, 977, 'sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (138, 1564, 'dictumst morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (277, 1116, 'eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (332, 1123, 'dolor quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (974, 923, 'suspendisse potenti');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (721, 1708, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (688, 1124, 'turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (114, 478, 'tempor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (95, 784, 'non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (865, 650, 'lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (97, 262, 'mi pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (823, 291, 'dui vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (519, 1129, 'nibh in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (251, 208, 'curabitur convallis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (844, 1433, 'faucibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (952, 944, 'libero ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (492, 105, 'tristique');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (981, 1249, 'faucibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (618, 1952, 'viverra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (912, 355, 'sapien varius');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (773, 1044, 'mauris eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (28, 782, 'id sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (605, 928, 'sed ante');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (820, 193, 'magna vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (994, 1916, 'volutpat in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (294, 1746, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (367, 1346, 'penatibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (201, 156, 'nullam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (846, 1322, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (781, 1258, 'nec nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (94, 1610, 'ut dolor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (454, 1536, 'proin');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (758, 1510, 'vulputate vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (227, 1389, 'purus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (526, 1445, 'rhoncus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (931, 431, 'ac lobortis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (895, 1090, 'turpis donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (671, 1392, 'habitasse platea');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (420, 410, 'tincidunt in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (447, 1197, 'maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (425, 1234, 'maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (315, 1934, 'pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (259, 1551, 'sagittis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (625, 1838, 'non ligula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (895, 985, 'nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (228, 152, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (960, 792, 'nullam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (486, 1316, 'enim');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (551, 1106, 'magna');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (170, 1966, 'in faucibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (119, 314, 'lorem integer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (753, 1814, 'lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (485, 410, 'ipsum praesent');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (724, 1756, 'consequat lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (900, 314, 'enim');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (902, 675, 'dapibus augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (518, 13, 'sapien dignissim');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (116, 143, 'dis parturient');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (914, 858, 'ullamcorper');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (852, 1552, 'aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (980, 1428, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (591, 350, 'etiam vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (289, 166, 'aenean fermentum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (638, 801, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (256, 91, 'vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (488, 907, 'convallis eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (614, 1184, 'quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (820, 1331, 'pulvinar');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (833, 1887, 'diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (132, 1100, 'elementum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (720, 1048, 'odio consequat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (911, 1491, 'duis bibendum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (694, 696, 'a nibh');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (512, 460, 'eget eleifend');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (251, 1528, 'non mauris');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (428, 1724, 'quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (369, 394, 'ipsum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (187, 603, 'quisque erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (576, 958, 'dictumst maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (714, 1249, 'pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (761, 1972, 'volutpat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (476, 1607, 'nulla nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (992, 935, 'ante');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (668, 440, 'odio');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (697, 1048, 'convallis eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (737, 1586, 'tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (437, 68, 'ac neque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (81, 419, 'sapien quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (781, 60, 'dolor morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (755, 1468, 'orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (913, 207, 'risus dapibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (399, 152, 'vivamus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (403, 825, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (865, 657, 'eros');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (157, 659, 'nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (754, 831, 'morbi non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (392, 142, 'adipiscing molestie');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (839, 151, 'primis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (783, 105, 'dolor morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (129, 1472, 'sed sagittis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (548, 1014, 'libero');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (574, 208, 'est risus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (432, 142, 'ligula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (107, 1119, 'proin');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (86, 1999, 'sed vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (597, 1146, 'tellus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (435, 544, 'pretium');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (909, 543, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (271, 585, 'vestibulum ante');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (290, 246, 'tellus nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (198, 510, 'tristique tortor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (579, 1727, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (585, 1298, 'ipsum ac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (499, 999, 'eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (905, 449, 'pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (155, 1083, 'lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (482, 377, 'dapibus augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (740, 1112, 'maecenas leo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (768, 955, 'vestibulum quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (711, 1777, 'tempus vivamus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (641, 384, 'congue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (58, 1692, 'faucibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (20, 1116, 'vulputate ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (518, 1009, 'ultrices erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (932, 353, 'ipsum dolor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (895, 869, 'venenatis lacinia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (476, 1254, 'et ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (168, 1336, 'penatibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (891, 1950, 'nascetur');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (92, 764, 'in imperdiet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (27, 1628, 'odio condimentum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (205, 1858, 'phasellus id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (780, 188, 'lobortis vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (559, 1079, 'rhoncus mauris');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (997, 1407, 'primis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (745, 768, 'dui');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (24, 1423, 'dictumst etiam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (525, 1696, 'ultrices phasellus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (682, 805, 'ipsum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (545, 722, 'turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (926, 1328, 'primis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (671, 1281, 'tortor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (271, 367, 'velit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (130, 698, 'odio elementum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (776, 271, 'felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (670, 210, 'venenatis tristique');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (868, 875, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (688, 1081, 'turpis elementum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (748, 1111, 'rhoncus aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (425, 976, 'morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (331, 1076, 'ligula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (525, 356, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (974, 975, 'tincidunt eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (173, 724, 'suspendisse accumsan');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (26, 1733, 'habitasse');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (520, 237, 'ultrices mattis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (119, 265, 'dolor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (341, 290, 'sapien iaculis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (66, 359, 'eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (833, 1311, 'pharetra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (552, 785, 'pretium');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (211, 1096, 'tincidunt nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (200, 1595, 'quis orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (154, 1120, 'rhoncus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (320, 262, 'lacinia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (517, 1098, 'suspendisse potenti');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (198, 1203, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (255, 1050, 'nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (299, 424, 'porttitor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (313, 889, 'eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (215, 187, 'proin');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (985, 165, 'penatibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (489, 1468, 'primis in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (976, 1807, 'nulla ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (749, 542, 'primis in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (66, 168, 'duis bibendum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (949, 35, 'orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (236, 1854, 'morbi porttitor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (234, 173, 'magnis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (104, 673, 'at nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (141, 1187, 'scelerisque mauris');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (134, 1682, 'posuere');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (12, 480, 'rutrum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (446, 462, 'quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (100, 931, 'ultrices phasellus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (670, 951, 'pretium quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (216, 1452, 'pellentesque viverra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (110, 673, 'quis libero');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (880, 1183, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (546, 679, 'dui');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (966, 502, 'massa id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (600, 732, 'porta');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (280, 1492, 'praesent');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (950, 612, 'elit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (730, 570, 'dui nec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (198, 834, 'at velit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (113, 1795, 'elementum eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (761, 1160, 'magna');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (162, 1649, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (762, 918, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (552, 57, 'eget tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (475, 989, 'metus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (324, 1942, 'convallis nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (972, 1526, 'convallis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (925, 1385, 'tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (335, 1509, 'tincidunt in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (288, 360, 'quis turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (118, 861, 'lacus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (248, 64, 'justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (653, 978, 'orci nullam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (286, 1921, 'et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (239, 45, 'ipsum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (39, 1025, 'ante vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (141, 1706, 'volutpat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (230, 1756, 'lacinia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (421, 304, 'tempus vivamus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (13, 994, 'sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (399, 1399, 'quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (224, 2, 'aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (90, 958, 'vel enim');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (545, 947, 'aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (77, 832, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (118, 585, 'nisl nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (633, 1351, 'mus etiam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (688, 602, 'amet sem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (114, 362, 'gravida sem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (887, 1512, 'felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (716, 1577, 'suspendisse accumsan');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (165, 194, 'eleifend');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (587, 1981, 'gravida nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (665, 1656, 'vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (678, 200, 'suspendisse potenti');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (105, 194, 'sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (906, 451, 'pede venenatis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (469, 557, 'amet justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (333, 1221, 'tincidunt eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (57, 146, 'felis eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (139, 1998, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (550, 1221, 'enim lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (522, 1625, 'purus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (535, 1117, 'sem sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (111, 1339, 'varius');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (55, 1914, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (468, 975, 'maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (31, 1496, 'elementum ligula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (347, 1444, 'sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (346, 1926, 'scelerisque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (89, 947, 'felis fusce');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (834, 863, 'mauris laoreet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (39, 447, 'et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (9, 654, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (955, 549, 'hac habitasse');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (427, 858, 'pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (217, 1429, 'tristique tortor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (128, 561, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (237, 112, 'in faucibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (672, 1629, 'lacus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (570, 96, 'phasellus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (70, 1352, 'lacinia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (675, 433, 'nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (204, 1135, 'tempus vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (277, 1594, 'sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (412, 580, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (783, 311, 'nibh in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (931, 1293, 'nisl aenean');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (829, 1529, 'non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (506, 578, 'platea dictumst');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (364, 1039, 'ligula pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (602, 1532, 'integer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (195, 1078, 'consequat morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (654, 808, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (902, 309, 'scelerisque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (407, 522, 'pede justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (303, 1764, 'augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (499, 1751, 'tempus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (716, 1151, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (444, 1870, 'eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (717, 1606, 'diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (835, 1302, 'aenean');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (487, 1655, 'sed augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (658, 1048, 'a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (901, 496, 'nullam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (920, 200, 'interdum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (944, 541, 'luctus cum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (678, 1268, 'ac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (611, 1287, 'lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (19, 477, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (46, 694, 'at dolor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (589, 971, 'enim lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (824, 1888, 'est');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (437, 210, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (370, 1909, 'maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (129, 605, 'magna vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (44, 107, 'quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (504, 833, 'suspendisse potenti');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (351, 1856, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (926, 412, 'quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (259, 336, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (664, 1744, 'semper');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (511, 1041, 'commodo vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (274, 532, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (300, 1413, 'ipsum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (841, 104, 'magna');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (754, 439, 'est congue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (283, 810, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (852, 515, 'nec nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (326, 7, 'convallis duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (333, 1405, 'nam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (920, 677, 'aliquet ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (642, 359, 'mattis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (492, 850, 'volutpat convallis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (726, 868, 'sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (678, 1994, 'nulla eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (97, 1367, 'sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (670, 524, 'blandit nam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (230, 1469, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (278, 583, 'est');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (717, 968, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (387, 91, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (150, 978, 'accumsan');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (562, 332, 'integer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (888, 1024, 'vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (799, 507, 'sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (651, 589, 'arcu adipiscing');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (516, 1705, 'quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (345, 1941, 'dui');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (369, 86, 'est quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (952, 791, 'eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (742, 503, 'lacus morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (906, 961, 'vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (885, 1003, 'adipiscing molestie');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (990, 588, 'cras in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (413, 1632, 'turpis elementum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (171, 354, 'lacus curabitur');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (783, 1111, 'vel est');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (822, 1178, 'nec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (67, 176, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (581, 430, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (317, 1171, 'sollicitudin');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (419, 317, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (948, 1428, 'sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (202, 1241, 'cursus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (37, 1834, 'tincidunt eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (607, 407, 'eu tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (804, 385, 'ut massa');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (244, 1596, 'bibendum morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (224, 1835, 'cubilia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (238, 721, 'molestie sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (210, 1251, 'eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (838, 342, 'iaculis diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (536, 514, 'natoque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (185, 145, 'nulla sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (872, 119, 'aenean');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (708, 1484, 'tempus vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (7, 478, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (778, 358, 'consectetuer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (945, 1842, 'blandit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (287, 41, 'ultrices phasellus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (818, 1910, 'eleifend donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (45, 13, 'hac habitasse');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (407, 603, 'sapien urna');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (687, 1345, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (297, 805, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (613, 1227, 'pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (761, 1097, 'purus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (284, 1599, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (279, 591, 'primis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (157, 872, 'nisl nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (622, 1648, 'quisque erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (827, 895, 'bibendum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (58, 184, 'nunc proin');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (949, 1125, 'vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (112, 1158, 'tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (584, 39, 'lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (777, 105, 'lacus curabitur');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (291, 1042, 'molestie hendrerit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (739, 1336, 'enim');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (58, 474, 'sapien urna');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (886, 1485, 'placerat praesent');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (608, 694, 'elementum in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (422, 1116, 'donec quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (718, 560, 'faucibus accumsan');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (105, 692, 'suscipit nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (941, 883, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (155, 1774, 'integer ac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (396, 1094, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (238, 1435, 'adipiscing elit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (256, 971, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (824, 1804, 'in sagittis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (120, 1714, 'sem sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (888, 1503, 'nec dui');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (380, 1955, 'leo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (770, 1788, 'eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (422, 1567, 'nunc viverra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (685, 526, 'posuere');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (531, 849, 'sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (922, 507, 'montes');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (862, 1950, 'donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (453, 429, 'feugiat non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (885, 1680, 'fusce congue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (122, 501, 'potenti in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (150, 654, 'nulla facilisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (41, 1972, 'et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (928, 1425, 'nibh fusce');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (935, 882, 'vestibulum quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (567, 1063, 'in hac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (986, 1143, 'donec diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (737, 1039, 'vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (805, 875, 'vestibulum sagittis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (111, 1026, 'potenti');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (68, 538, 'vestibulum aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (629, 1164, 'et ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (30, 647, 'nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (666, 387, 'elit proin');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (863, 26, 'praesent blandit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (141, 142, 'cubilia curae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (401, 1660, 'aliquet maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (116, 1217, 'neque libero');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (685, 612, 'nam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (802, 627, 'in ante');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (684, 101, 'mi nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (101, 1832, 'quis justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (952, 1569, 'erat tortor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (425, 978, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (267, 814, 'sagittis nam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (94, 838, 'pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (529, 362, 'nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (569, 181, 'quis orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (685, 1199, 'duis faucibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (704, 1641, 'justo in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (129, 185, 'in felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (862, 885, 'molestie lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (434, 1949, 'viverra dapibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (658, 110, 'pellentesque eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (229, 919, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (142, 1113, 'luctus et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (139, 609, 'condimentum id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (161, 917, 'aenean lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (352, 1263, 'fusce consequat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (75, 884, 'nibh in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (882, 756, 'rhoncus aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (33, 1066, 'arcu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (903, 426, 'vel nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (743, 1374, 'eleifend');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (586, 604, 'et commodo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (444, 1121, 'luctus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (773, 1181, 'ipsum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (597, 769, 'eu massa');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (948, 1135, 'aliquet at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (357, 810, 'felis sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (214, 1705, 'erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (359, 332, 'luctus et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (464, 1078, 'adipiscing elit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (897, 1868, 'nullam varius');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (173, 410, 'pede lobortis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (240, 219, 'sapien cum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (905, 560, 'vel est');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (975, 1509, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (311, 1482, 'sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (313, 1962, 'nunc purus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (736, 179, 'lectus aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (642, 851, 'accumsan');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (64, 649, 'curabitur');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (116, 524, 'aliquam augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (331, 339, 'venenatis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (440, 1066, 'libero ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (211, 1538, 'nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (363, 733, 'venenatis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (335, 1854, 'mi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (711, 986, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (722, 1710, 'nisl duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (111, 596, 'lectus in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (400, 1667, 'nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (166, 1897, 'vulputate justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (233, 1254, 'sem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (442, 958, 'quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (168, 1883, 'metus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (997, 1900, 'quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (473, 288, 'magnis dis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (605, 1375, 'urna pretium');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (174, 1711, 'lectus aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (66, 32, 'tincidunt nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (355, 643, 'donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (326, 71, 'luctus et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (142, 1581, 'in lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (979, 810, 'potenti nullam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (774, 994, 'sociis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (109, 768, 'quam turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (960, 533, 'et eros');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (750, 1343, 'ut massa');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (351, 1648, 'elementum pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (43, 170, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (195, 33, 'tristique');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (75, 1921, 'fermentum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (435, 679, 'nullam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (487, 1710, 'cras in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (859, 469, 'sagittis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (560, 1762, 'nulla tellus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (492, 947, 'integer non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (676, 730, 'quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (953, 151, 'nisi venenatis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (786, 182, 'laoreet ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (440, 1829, 'consequat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (487, 1346, 'nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (375, 247, 'pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (770, 1812, 'luctus et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (980, 951, 'vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (472, 1773, 'nec nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (543, 1186, 'praesent lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (51, 1635, 'morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (330, 1681, 'ac tellus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (604, 123, 'leo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (951, 1084, 'sollicitudin mi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (317, 1524, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (833, 409, 'pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (305, 94, 'at dolor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (278, 463, 'leo odio');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (602, 1137, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (787, 1737, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (348, 1740, 'lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (524, 1630, 'nibh');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (109, 321, 'nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (677, 911, 'est');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (688, 1233, 'platea dictumst');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (774, 1061, 'pharetra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (733, 1866, 'diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (118, 143, 'vitae nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (177, 340, 'enim');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (611, 1602, 'elit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (484, 768, 'nisl nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (746, 1048, 'at turpis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (72, 1487, 'sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (202, 1985, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (611, 724, 'quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (558, 1488, 'gravida nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (241, 978, 'in imperdiet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (41, 974, 'vulputate ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (945, 1712, 'diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (808, 858, 'duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (267, 1114, 'ligula vehicula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (947, 58, 'venenatis lacinia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (73, 1329, 'blandit ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (530, 781, 'penatibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (25, 1709, 'pellentesque quisque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (911, 577, 'varius nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (281, 1812, 'luctus et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (158, 1651, 'vulputate vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (571, 1653, 'donec pharetra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (942, 830, 'purus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (547, 86, 'elementum pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (642, 353, 'aenean lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (789, 890, 'lobortis convallis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (569, 1991, 'aenean');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (773, 1207, 'erat quisque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (590, 876, 'urna pretium');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (318, 1290, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (386, 101, 'vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (842, 305, 'sagittis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (632, 813, 'duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (84, 1975, 'nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (73, 465, 'gravida');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (188, 1644, 'id nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (66, 722, 'orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (873, 497, 'felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (638, 1863, 'nam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (479, 795, 'sapien urna');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (872, 1492, 'sem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (455, 1099, 'nulla eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (445, 1472, 'massa tempor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (530, 1834, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (750, 1400, 'magna bibendum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (142, 1098, 'cubilia curae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (437, 94, 'proin leo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (316, 926, 'nec euismod');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (188, 1697, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (436, 1133, 'sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (799, 985, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (793, 584, 'consequat nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (64, 1969, 'volutpat dui');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (590, 1355, 'at diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (999, 1149, 'pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (471, 18, 'est');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (529, 446, 'lectus aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (781, 1333, 'pede morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (771, 1116, 'hac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (905, 1218, 'suspendisse ornare');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (74, 1946, 'aenean fermentum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (161, 1949, 'quis orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (164, 998, 'diam in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (692, 1533, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (817, 1618, 'blandit lacinia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (256, 1970, 'tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (757, 497, 'felis fusce');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (331, 1003, 'rutrum nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (952, 1873, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (942, 1585, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (718, 1590, 'orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (171, 183, 'eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (961, 332, 'nec condimentum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (461, 847, 'pede posuere');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (905, 1461, 'nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (654, 1926, 'eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (391, 121, 'nullam sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (658, 1115, 'congue elementum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (472, 1601, 'pretium iaculis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (947, 260, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (137, 781, 'vivamus vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (180, 1585, 'dui');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (780, 1714, 'vivamus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (161, 1978, 'pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (52, 146, 'curabitur in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (351, 1392, 'proin');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (585, 651, 'quam a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (850, 180, 'habitasse');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (971, 1644, 'risus dapibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (506, 1531, 'vel nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (567, 1636, 'sapien sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (492, 1232, 'morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (411, 1373, 'bibendum felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (458, 1965, 'fringilla rhoncus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (657, 1021, 'vel nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (360, 440, 'a');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (359, 975, 'dictumst');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (28, 1041, 'mauris');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (673, 883, 'vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (21, 1696, 'sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (482, 86, 'parturient montes');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (851, 1095, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (682, 1613, 'adipiscing lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (862, 1102, 'etiam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (363, 824, 'mauris');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (766, 629, 'cursus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (686, 1689, 'ornare imperdiet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (997, 1337, 'viverra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (602, 1678, 'ornare consequat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (428, 23, 'nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (469, 957, 'pede malesuada');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (98, 1879, 'curae duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (894, 1896, 'non velit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (954, 1998, 'integer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (374, 1368, 'sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (99, 1386, 'consectetuer eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (405, 1011, 'erat quisque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (973, 1004, 'a suscipit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (19, 1974, 'luctus tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (85, 1951, 'at lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (667, 1839, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (93, 998, 'mattis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (527, 1083, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (358, 829, 'accumsan');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (649, 808, 'cursus vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (38, 1244, 'faucibus orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (134, 1356, 'faucibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (628, 127, 'non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (954, 1753, 'eget orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (853, 114, 'tristique tortor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (814, 1391, 'mus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (570, 1935, 'pede morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (660, 1202, 'cras');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (965, 1369, 'curae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (950, 1651, 'nascetur');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (248, 1077, 'sem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (87, 1455, 'orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (932, 1498, 'vel ipsum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (610, 780, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (150, 1086, 'est lacinia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (293, 310, 'donec diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (304, 925, 'donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (312, 218, 'hac habitasse');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (165, 1445, 'pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (38, 947, 'pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (684, 653, 'velit donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (97, 22, 'id nisl');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (334, 283, 'mi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (436, 998, 'non ligula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (753, 132, 'lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (972, 422, 'nisi eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (68, 1891, 'sit amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (781, 1667, 'sed interdum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (112, 195, 'tempor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (197, 558, 'justo in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (701, 1517, 'nisi volutpat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (617, 632, 'curabitur');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (302, 1303, 'orci luctus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (848, 144, 'quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (113, 1622, 'arcu sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (305, 452, 'vulputate elementum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (988, 251, 'mauris non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (55, 882, 'nec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (33, 678, 'interdum in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (981, 854, 'aliquet maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (88, 1344, 'in felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (830, 1016, 'penatibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (160, 991, 'elementum ligula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (875, 99, 'vestibulum ante');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (782, 291, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (167, 532, 'luctus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (697, 1320, 'suscipit ligula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (356, 443, 'quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (252, 1674, 'nulla facilisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (136, 858, 'mattis odio');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (870, 544, 'elementum ligula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (926, 465, 'nunc viverra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (29, 987, 'nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (873, 1801, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (570, 109, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (599, 938, 'tristique');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (429, 1397, 'vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (836, 1447, 'pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (94, 1268, 'nisl nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (50, 1621, 'vulputate nonummy');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (948, 1330, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (896, 1750, 'vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (766, 1313, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (195, 332, 'est donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (724, 1599, 'consequat nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (84, 1862, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (345, 1249, 'velit donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (737, 616, 'eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (504, 352, 'diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (78, 658, 'etiam justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (18, 1409, 'erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (796, 395, 'bibendum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (60, 1943, 'tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (537, 1151, 'ultrices posuere');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (400, 786, 'mauris eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (362, 982, 'non mi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (916, 689, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (343, 443, 'quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (51, 425, 'duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (908, 584, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (367, 1432, 'primis in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (585, 329, 'imperdiet sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (763, 1710, 'duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (498, 1828, 'id');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (374, 117, 'natoque penatibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (785, 1292, 'auctor sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (320, 1648, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (577, 718, 'lacus purus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (753, 1442, 'mauris');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (535, 1995, 'quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (327, 326, 'sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (473, 1237, 'erat nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (342, 848, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (349, 505, 'mi pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (295, 1874, 'ipsum praesent');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (45, 91, 'turpis adipiscing');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (410, 270, 'platea');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (89, 923, 'diam nam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (63, 711, 'pellentesque eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (144, 653, 'ligula vehicula');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (869, 1102, 'primis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (657, 1975, 'in sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (364, 1063, 'mauris');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (884, 814, 'morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (479, 1910, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (899, 1917, 'sagittis dui');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (254, 804, 'orci luctus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (980, 680, 'nunc purus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (45, 676, 'eu orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (842, 1342, 'metus aenean');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (966, 877, 'erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (612, 1633, 'ultrices mattis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (679, 1451, 'sociis natoque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (852, 1822, 'diam cras');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (115, 362, 'etiam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (453, 1947, 'sagittis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (918, 1325, 'eu tincidunt');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (615, 1329, 'pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (773, 692, 'nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (749, 1064, 'convallis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (333, 690, 'nullam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (613, 304, 'orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (469, 563, 'aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (29, 1772, 'cubilia curae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (118, 800, 'ac diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (312, 1151, 'elementum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (858, 1023, 'in tempor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (219, 923, 'consectetuer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (799, 209, 'sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (497, 63, 'quis augue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (162, 1298, 'ac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (958, 1600, 'neque sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (770, 1626, 'aliquam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (494, 1052, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (437, 1399, 'maecenas');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (742, 438, 'lectus pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (846, 246, 'molestie lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (559, 1701, 'duis consequat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (200, 2, 'est');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (249, 741, 'pulvinar');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (988, 1333, 'erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (401, 4, 'congue');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (568, 1002, 'dapibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (272, 1091, 'porttitor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (489, 959, 'pharetra magna');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (747, 1392, 'felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (84, 986, 'ut ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (950, 1107, 'dui');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (857, 1026, 'ullamcorper');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (777, 853, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (157, 932, 'maecenas leo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (102, 1886, 'pede justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (705, 1313, 'donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (335, 1582, 'sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (655, 1296, 'nisi nam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (417, 505, 'sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (900, 1477, 'amet cursus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (102, 1292, 'dui proin');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (886, 1933, 'convallis tortor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (293, 1304, 'non quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (609, 227, 'elementum pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (863, 459, 'sociis natoque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (464, 394, 'lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (47, 956, 'quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (156, 311, 'aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (805, 410, 'libero quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (285, 301, 'nisi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (51, 181, 'eleifend');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (893, 1362, 'integer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (939, 1861, 'vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (802, 1633, 'semper');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (499, 49, 'elementum eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (68, 1747, 'diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (273, 1377, 'sed vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (949, 1873, 'duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (29, 1967, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (583, 562, 'ornare');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (541, 1139, 'mattis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (535, 1716, 'vel nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (610, 1051, 'non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (456, 942, 'aliquam quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (737, 476, 'adipiscing');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (316, 394, 'potenti');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (575, 789, 'rhoncus sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (255, 1595, 'consequat nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (4, 221, 'posuere felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (786, 1799, 'consectetuer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (604, 331, 'justo in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (322, 1182, 'donec diam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (385, 140, 'porta');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (317, 843, 'vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (367, 1634, 'velit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (754, 546, 'gravida');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (936, 1636, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (426, 1762, 'ante ipsum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (370, 1638, 'suspendisse');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (905, 1516, 'dui luctus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (265, 235, 'praesent');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (999, 1224, 'sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (480, 632, 'quis justo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (687, 330, 'mauris vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (24, 1050, 'lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (993, 1213, 'penatibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (816, 1541, 'in ante');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (947, 1196, 'mauris');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (642, 60, 'tristique est');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (195, 124, 'adipiscing');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (811, 939, 'tortor duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (512, 577, 'vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (309, 1613, 'lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (947, 303, 'vestibulum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (867, 1337, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (599, 1555, 'in felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (462, 1639, 'praesent blandit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (470, 1068, 'massa');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (650, 963, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (92, 1148, 'morbi non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (107, 1948, 'lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (961, 844, 'curabitur at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (674, 918, 'vivamus metus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (95, 1832, 'porttitor lacus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (613, 1354, 'neque sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (437, 1238, 'sapien');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (974, 1415, 'tortor eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (566, 1958, 'dapibus at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (658, 297, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (94, 1943, 'sit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (373, 548, 'lobortis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (753, 1130, 'platea dictumst');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (689, 1649, 'venenatis tristique');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (52, 293, 'at nunc');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (906, 158, 'iaculis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (697, 1291, 'metus aenean');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (936, 1183, 'erat eros');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (256, 968, 'lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (401, 1673, 'vulputate');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (166, 1413, 'nibh');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (487, 400, 'non quam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (724, 1114, 'purus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (938, 759, 'felis donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (247, 1752, 'morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (901, 1551, 'volutpat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (637, 1325, 'montes nascetur');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (586, 727, 'dictumst');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (556, 14, 'platea');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (382, 1624, 'sem fusce');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (159, 1150, 'nibh in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (210, 1659, 'massa donec');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (38, 3, 'eu');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (840, 1096, 'cubilia curae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (151, 885, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (305, 1169, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (214, 1978, 'donec odio');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (951, 531, 'quisque erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (242, 1254, 'platea dictumst');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (109, 1352, 'ultrices aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (422, 170, 'quis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (109, 1551, 'quisque porta');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (684, 597, 'vestibulum eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (982, 1851, 'posuere');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (469, 1871, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (175, 129, 'accumsan odio');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (977, 610, 'potenti');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (303, 437, 'vel ipsum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (975, 903, 'consectetuer adipiscing');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (573, 1466, 'volutpat eleifend');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (138, 37, 'odio');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (144, 1488, 'nisi volutpat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (408, 1520, 'nulla');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (397, 554, 'nec dui');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (518, 692, 'primis in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (478, 1645, 'mauris eget');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (870, 992, 'ridiculus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (912, 1658, 'justo etiam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (184, 950, 'dui');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (885, 1833, 'mi pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (878, 358, 'dictumst etiam');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (569, 381, 'felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (627, 300, 'at feugiat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (958, 1633, 'justo pellentesque');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (149, 330, 'non mattis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (929, 1439, 'luctus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (881, 101, 'donec pharetra');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (510, 994, 'sodales');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (261, 829, 'aenean lectus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (949, 2000, 'lobortis vel');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (521, 88, 'malesuada');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (92, 1494, 'imperdiet et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (232, 1630, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (311, 1463, 'morbi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (466, 1184, 'volutpat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (718, 464, 'non velit');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (742, 253, 'luctus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (69, 1068, 'odio curabitur');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (181, 292, 'laoreet ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (708, 375, 'est');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (252, 228, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (451, 522, 'proin interdum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (700, 800, 'erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (897, 1793, 'lacinia');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (630, 440, 'mi');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (152, 1040, 'tortor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (989, 1696, 'consectetuer adipiscing');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (506, 1453, 'maecenas leo');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (601, 768, 'at feugiat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (913, 986, 'tristique');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (400, 1291, 'sapien urna');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (973, 1618, 'in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (567, 1760, 'in porttitor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (278, 1875, 'non');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (755, 1948, 'sapien urna');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (864, 639, 'erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (749, 202, 'amet consectetuer');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (954, 1439, 'in felis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (811, 1677, 'at');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (145, 587, 'duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (933, 1711, 'habitasse');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (258, 1006, 'at dolor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (872, 258, 'platea');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (175, 869, 'venenatis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (834, 1576, 'ipsum ac');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (730, 527, 'dapibus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (186, 1830, 'ultrices');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (891, 108, 'fusce');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (120, 1222, 'vitae');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (664, 981, 'nullam porttitor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (782, 1662, 'ut');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (932, 1515, 'duis bibendum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (424, 316, 'faucibus orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (772, 737, 'sodales');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (746, 96, 'porttitor');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (551, 624, 'felis sed');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (756, 1314, 'tellus in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (428, 1754, 'ultrices aliquet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (944, 1138, 'adipiscing');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (611, 1070, 'convallis duis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (452, 1938, 'faucibus orci');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (794, 180, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (392, 91, 'pede');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (801, 1573, 'interdum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (806, 724, 'curabitur convallis');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (306, 226, 'justo in');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (588, 1035, 'feugiat et');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (541, 390, 'lacus');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (892, 1864, 'erat');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (433, 1974, 'fermentum');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (10, 1500, 'at lorem');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (807, 166, 'amet');
insert into RECIPE_DUTY (employeeid, recipeid, dutydescription) values (326, 459, 'eget nunc');
