-- Transactoin#5
CREATE INDEX IDX_EMP_ID_DATE ON EMPLOYEE(EMPLOYEEID ASC, DATECONTRACTFIN ASC);
-- Transactoin#2
CREATE INDEX IDX_EMP_POSID_DATE ON EMPLOYEE(POSITIONID ASC, DATECONTRACTFIN ASC);
-- Transaction #4
CREATE INDEX IDX_SUP_ID_REL ON SUPPLIER(SUPPLIERID ASC, RELIABILITY ASC);
-- Transaction #3
CREATE INDEX IDX_INGRST_ID_IMISS ON INGREDIENT_STOCK(INGRSTOCKID ASC, WEIGHTMISSING ASC);