-- Transactoin#5
CREATE INDEX IDX_EMP_ID_DATE ON EMPLOYEE(EMPLOYEEID ASC, DATECONTRACTFIN ASC);
-- Transactoin#2
CREATE INDEX IDX_SUP_REQ_INGRID_STATE_DATE on SUPPLY_REQUEST(INGRSTOCKID,STATE,DATEREQUEST);
-- Transactoin#2
CREATE INDEX IDX_EMP_POSID_DATE ON EMPLOYEE(POSITIONID,DATECONTRACTFIN);