DROP TABLE TRIGGER_LOG;
/
CREATE TABLE TRIGGER_LOG
(
    LOG_ID INT NOT NULL,
    LOG_REC VARCHAR(50),
    CONSTRAINT TR_LOG_PK PRIMARY KEY(LOG_ID) 
);
/
INSERT INTO TRIGGER_LOG VALUES(1,'TRY REC');
/
CREATE OR REPLACE TRIGGER RECIPE_TRIG
AFTER INSERT ON RECIPE
DECLARE
    max_id NUMBER;
BEGIN
    SELECT MAX(LOG_ID)+1 INTO max_id    
    FROM TRIGGER_LOG;
    
    INSERT INTO TRIGGER_LOG VALUES(max_id,'RECIPE TRIGGER #1');
    DBMS_OUTPUT.PUT_LINE('1');    
    
    SELECT MAX(POSITIONID)+1 INTO max_id
    FROM POSITION;
    INSERT INTO POSITION VALUES(max_id,'BOSS',9999);
END;
/
CREATE OR REPLACE TRIGGER POS_TRIG
AFTER INSERT ON POSITION
DECLARE
    max_id NUMBER;
BEGIN
    SELECT MAX(LOG_ID)+1 INTO max_id    
    FROM TRIGGER_LOG;
    
    INSERT INTO TRIGGER_LOG VALUES(max_id,'POSITION TRIGGER #2');
    DBMS_OUTPUT.PUT_LINE('2');
    
    SELECT MAX(INGRSTOCKID)+1 INTO max_id
    FROM INGREDIENT_STOCK;
    INSERT INTO INGREDIENT_STOCK VALUES(max_id,'PANACEA',9999,9999);
END;
/
CREATE OR REPLACE TRIGGER INGR_ST_TRIG
AFTER INSERT ON INGREDIENT_STOCK
DECLARE
    max_id NUMBER;
BEGIN
    SELECT MAX(LOG_ID)+1 INTO max_id    
    FROM TRIGGER_LOG;
    
    INSERT INTO TRIGGER_LOG VALUES(max_id,'INGREDIENT STOCK TRIGGER #3');
    DBMS_OUTPUT.PUT_LINE('3');        
    
    SELECT MAX(RECIPEID)+1 INTO max_id
    FROM RECIPE;
    INSERT INTO RECIPE VALUES(max_id,'PANACEA','PANACEA',999,'17/11/2016','AVAILABLE');
END;
/
DECLARE
    max_id NUMBER;
BEGIN
    SELECT MAX(RECIPEID)+1 INTO max_id
    FROM RECIPE;
    INSERT INTO RECIPE VALUES(max_id,'PNA','PANACEA',999,'17/11/2016','AVAILABLE');
END;