DROP TABLE TRIGGER_RACE;
/
CREATE TABLE TRIGGER_RACE
(
    LOG_ID INT NOT NULL,
    LOG_REC VARCHAR(50),
    CONSTRAINT TR_RACE_PK PRIMARY KEY(LOG_ID) 
);
/
INSERT INTO TRIGGER_RACE VALUES(1,'TRY REC');
/
CREATE OR REPLACE TRIGGER TRIG_RACE_1
AFTER INSERT ON EMPLOYEE
DECLARE
    max_id NUMBER;
BEGIN
    SELECT MAX(LOG_ID)+1 INTO max_id    
    FROM TRIGGER_RACE;
    
    INSERT INTO TRIGGER_RACE VALUES(max_id,'TRIGGER #1');
    DBMS_OUTPUT.PUT_LINE('TRIGGER #1');        
END;
/

CREATE OR REPLACE TRIGGER TRIG_RACE_2
AFTER INSERT ON EMPLOYEE
DECLARE
    max_id NUMBER;
BEGIN
    SELECT MAX(LOG_ID)+1 INTO max_id    
    FROM TRIGGER_RACE;
    
    INSERT INTO TRIGGER_RACE VALUES(max_id,'TRIGGER #2');
    DBMS_OUTPUT.PUT_LINE('TRIGGER #2');    
END;
/

CREATE OR REPLACE TRIGGER TRIG_RACE_3
AFTER INSERT ON EMPLOYEE
DECLARE
    max_id NUMBER;
BEGIN
    SELECT MAX(LOG_ID)+1 INTO max_id    
    FROM TRIGGER_RACE;
    
    INSERT INTO TRIGGER_RACE VALUES(max_id,'TRIGGER #3');
    DBMS_OUTPUT.PUT_LINE('TRIGGER #3');    
END;
/

DECLARE
    max_id NUMBER;
BEGIN
    SELECT MAX(EMPLOYEEID)+1 INTO max_id
    FROM EMPLOYEE;
    INSERT INTO EMPLOYEE VALUES(max_id,'Test','Testich',SYSDATE+32,1);
END;