-- Active rule #3
SELECT * FROM EMPLOYEE WHERE EMPLOYEEID = -1;
SELECT SYSDATE FROM DUAL;

INSERT INTO EMPLOYEE (EMPLOYEEID, FIRSTNAME, LASTNAME, DATECONTRACTFIN,POSITIONID)
VALUES (-1, 'JAN','KOWALSKI','07.12.2016',22);

-- Active rule #4
SELECT * FROM INGREDIENT_STOCK WHERE INGRSTOCKID = 12776;
SELECT * FROM SUPPLIER_STOCK WHERE INGRSTOCKID = 12776;

SELECT *
FROM SUPPLY_REQUEST
WHERE REQUESTID = (SELECT MAX(REQUESTID) 
                    FROM SUPPLY_REQUEST);

INSERT INTO SUPPLIER_STOCK (SUPPLIERID, PRICE, WEIGHTAVAIL, DATEFRESHSUPPLY, INGRSTOCKID)
VALUES (459, 999, 999, '07.12.2016', 12776);

-- Active rule #5
UPDATE SUPPLY_REQUEST SET DATEREQUEST = (SELECT SYSDATE FROM DUAL)
WHERE REQUESTID = (SELECT MAX(REQUESTID)
                    FROM SUPPLY_REQUEST);

SELECT * FROM INGREDIENT_STOCK WHERE INGRSTOCKID = 12776;

SELECT *
FROM SUPPLY_REQUEST
WHERE REQUESTID = (SELECT MAX(REQUESTID) 
                    FROM SUPPLY_REQUEST);